apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: eW91ci1zZWNyZXQta2V5LWZvci1qd3Q=

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
type: Opaque
data:
  password: eW91cl9zZWN1cmVfcGFzc3dvcmRfaGVyZTI=